name: UserService CI

on:
  push:
    branches: [ "main" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build userservice
      run: |
        dotnet build --configuration Release UserService/UserService.csproj
  
  docker-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: UserService
          file: ./Dockerfile
          push: true
          tags: docker.io/rekkarten/userservice:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    
