name: UserService CI

on:
  push:
    paths:
      - 'UserService/**'
    branches:
      - main
    
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build userservice
      run: |
        dotnet build --configuration Release UserService/UserService.csproj
  
  docker-build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: ./UserService
          file: ./UserService/Dockerfile
          push: true
          tags: rekkarten/userservice:latest
    
    
